const products = [
  {
    name: "Classic Denim Jacket",
    code: 1298743,
    price: 89.99,
    category: "Outerwear",
    color: "1d3557_navy",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    rating: 4.5,
  },
  {
    name: "Silk Wrap Dress",
    code: 8374612,
    price: 120.5,
    category: "Dresses",
    color: "e63946_crimson",
    size: ["XS", "S", "M", "L"],
    brand: "Zudio",
    rating: 4.8,
  },
  {
    name: "Leather Chelsea Boots",
    code: 4567892,
    price: 145.0,
    category: "Footwear",
    color: "6d4c41_brown",
    size: [7, 8, 9, 10, 11],
    brand: "Westside",
    rating: 4.6,
  },
  {
    name: "Vintage Aviator Sunglasses",
    code: 9873451,
    price: 75.25,
    category: "Accessories",
    color: "000000_black",
    size: ["One Size"],
    brand: "H&M",
    rating: 4.4,
  },
  {
    name: "Formal Suit",
    code: 2354897,
    price: 250.0,
    category: "Suits",
    color: "2a9d8f_teal",
    size: ["M", "L", "XL"],
    brand: "Zudio",
    rating: 4.7,
  },
  {
    name: "High-Waisted Palazzo Pants",
    code: 6743981,
    price: 68.4,
    category: "Bottoms",
    color: "ffb703_mustard",
    size: ["S", "M", "L"],
    brand: "Westside",
    rating: 4.2,
  },
  {
    name: "Leather Belt",
    code: 5632178,
    price: 35.0,
    category: "Accessories",
    color: "8d5524_tan",
    size: ["S", "M", "L"],
    brand: "H&M",
    rating: 4.3,
  },
  {
    name: "Cashmere Scarf",
    code: 7124563,
    price: 45.0,
    category: "Accessories",
    color: "f1faee_white",
    size: ["One Size"],
    brand: "Zudio",
    rating: 4.5,
  },
  {
    name: "Slim-Fit Chinos",
    code: 9845761,
    price: 54.99,
    category: "Bottoms",
    color: "264653_olive",
    size: ["S", "M", "L", "XL"],
    brand: "Westside",
    rating: 4.4,
  },
  {
    name: "Running Shoes",
    code: 3218945,
    price: 110.5,
    category: "Footwear",
    color: "e76f51_red",
    size: [6, 7, 8, 9, 10, 11],
    brand: "H&M",
    rating: 4.6,
  },
  {
    name: "Casual T-Shirt",
    code: 2358476,
    price: 29.99,
    category: "Tops",
    color: "fcba03_yellow",
    size: ["S", "M", "L", "XL"],
    brand: "Zudio",
    rating: 4.0,
  },
  {
    name: "Printed Maxi Skirt",
    code: 9183745,
    price: 39.99,
    category: "Bottoms",
    color: "0a74da_blue",
    size: ["S", "M", "L"],
    brand: "Westside",
    rating: 4.5,
  },
  {
    name: "Sweatshirt",
    code: 1837459,
    price: 60.0,
    category: "Tops",
    color: "f4a261_orange",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    rating: 4.2,
  },
  {
    name: "Leopard Print Dress",
    code: 2938475,
    price: 80.5,
    category: "Dresses",
    color: "4e503b_leopard",
    size: ["XS", "S", "M", "L"],
    brand: "Zudio",
    rating: 4.3,
  },
  {
    name: "Black Ankle Boots",
    code: 4568327,
    price: 110.0,
    category: "Footwear",
    color: "000000_black",
    size: [7, 8, 9, 10, 11],
    brand: "Westside",
    rating: 4.5,
  },
  {
    name: "Cotton Polo Shirt",
    code: 7349281,
    price: 35.99,
    category: "Tops",
    color: "2a9d8f_teal",
    size: ["M", "L", "XL"],
    brand: "H&M",
    rating: 4.1,
  },
  {
    name: "Cargo Pants",
    code: 1928475,
    price: 59.99,
    category: "Bottoms",
    color: "264653_olive",
    size: ["S", "M", "L"],
    brand: "Zudio",
    rating: 4.3,
  },
  {
    name: "Aviator Sunglasses",
    code: 9384721,
    price: 45.0,
    category: "Accessories",
    color: "000000_black",
    size: ["One Size"],
    brand: "Westside",
    rating: 4.6,
  },
  {
    name: "Blazer",
    code: 5837291,
    price: 120.0,
    category: "Suits",
    color: "ff6347_tomato",
    size: ["M", "L", "XL"],
    brand: "H&M",
    rating: 4.7,
  },
  {
    name: "Floral Print Dress",
    code: 2837465,
    price: 89.99,
    category: "Dresses",
    color: "ffb703_mustard",
    size: ["S", "M", "L"],
    brand: "Zudio",
    rating: 4.4,
  },
  {
    name: "Chukka Boots",
    code: 9845732,
    price: 115.0,
    category: "Footwear",
    color: "6d4c41_brown",
    size: [8, 9, 10, 11],
    brand: "Westside",
    rating: 4.6,
  },
  {
    name: "Cardigan Sweater",
    code: 1827394,
    price: 50.99,
    category: "Tops",
    color: "f1faee_white",
    size: ["S", "M", "L"],
    brand: "H&M",
    rating: 4.5,
  },
  {
    name: "Bermuda Shorts",
    code: 9837456,
    price: 38.0,
    category: "Bottoms",
    color: "e63946_crimson",
    size: ["S", "M", "L"],
    brand: "Zudio",
    rating: 4.2,
  },
  {
    name: "Double-Breasted Blazer",
    code: 9837245,
    price: 160.0,
    category: "Suits",
    color: "2a9d8f_teal",
    size: ["M", "L", "XL"],
    brand: "Westside",
    rating: 4.8,
  },
  {
    name: "High-Heeled Sandals",
    code: 7123945,
    price: 75.0,
    category: "Footwear",
    color: "e76f51_red",
    size: [6, 7, 8, 9, 10],
    brand: "H&M",
    rating: 4.5,
  },
];

export default products;
